### ISSUE TITLE
A better artistic qrcode website...

### ISSUE THREAD

**Issue by yaojunWang** [x-hw/amazing-qr#44]
[LEMA](http://lema.design)  http://lema.design if  want free ?  I have some way...

**Comment by cys138138** [comment]
您好，你的邮件我已收到！

**Comment by zhangtinghai** [comment]
收到。。

**Comment by kuaij** [comment]
您好！

    您正在找回密码，为确保是你本人操作，请在邮箱验证码输入框输入下方验证码：


    
        
            658360
        
    


        如果这不是你本人所为，请忽略。请勿向任何人泄漏您收到的验证码。


    
        
    


        冬奥小助 账号团队敬上
